name: 🚀 Deploy NestJS Blog Backend API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "/root/torres_isaac/Tienda-NBA-backend"

      - name: Run deploy commands on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /root/torres_isaac/Tienda-NBA-backend
            
            echo "Matando proceso en puerto 3026 (si existe)..."
            sudo lsof -t -i:3026 | xargs -r sudo kill -9
            
            echo "Escribiendo archivo .env"
            echo "${{ secrets.ENV_FILE }}" > .env

            echo "Instalando dependencias..."
            npm install
            
            echo "Construyendo proyecto..."
            npm run build
            
            echo "Reiniciando PM2..."
            pm2 stop tienda_nba_app || true
            pm2 delete tienda_nba_app || true
            
            # Asegúrate que esta ruta sea la correcta para tu main.js compilado
            pm2 start dist/main.js --name tienda_nba_app
            
